spring:
  application:
    name: market-express
  data:
    mongodb:
      uri: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}?retryWrites=true&w=majority&appName=${DB_HOST}

jwt:
  key: ${JWT_KEY}

api:
  key: ${API_KEY}

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  from-number: ${TWILIO_FROM_NUMBER}

reniec:
  url: ${RENIEC_URL}
  token: ${RENIEC_TOKEN}

cors:
  allowed:
    origin: ${CORS_ALLOWED_ORIGIN}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    mongo:
      enabled: true
  security:
    enabled: false  # Deshabilitar la seguridad de Actuator (NO recomendado en producción)
logging:
  level:
    org.springframework.security: DEBUG

firebase:
  service:
    account-key: ${FIREBASE_SERVICE_ACCOUNT_KEY}
  bucket:
    name: ${FIREBASE_BUCKET_NAME}
